_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.13.4
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
            "2":
                - 1
                - 41
                - 49
                - 51
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
                - 55
            "4": 3.13.4
            "5": 0.20.1
            "8":
                - 3
            "10":
                - 20
            "12": 0.20.1
            "13": windows-amd64
architecture:
    value: ResNet
dataset:
    value: manuel-yao/pokemon-keras-community
epochs:
    value: 10
learning_rate:
    value: 0.001
momentum:
    value: 0.9
